[project]
name = "mysystemdown"
version = "0.1.0"
description = "MySystemDown is a healthy check system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "djangorestframework>=3.16.1",
]
